language: node_js
node_js:
- node
before_install: if [[ `npm -v` != 5.3* ]]; then npm i -g npm@5.3.0; fi
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build
- npm run dist
after_deploy:
- sh ./update-release.sh
deploy:
  provider: npm
  email: t.vandam@wearetriple.com
  api_key:
    secure: HZZRasmfaMDdz675sp3j4YXwoYXgkwGiO6OwO8x7trQTwpW7sz5CTpoy2LlmQUrF1zAazIRw2FwdXlAeqwskK5vEO/WZMltQ+6iUxDdj4jYQamByHuT98bVL7F40Ou8hu32FEaafQOKdABHyfWKQtbRvGDcCdTp86UFIUDiDim37vgHMVMQ1Ct8YMiZ2HerYSH3aOorFRIfxglF+NBLnkx+GqiF3VHOhbuNZDzZsl4+NquIpqVlXzCzCQsZ7af7YNgVoX5Kqg9Qj/xM5Bh9rLigdDBiXXpLroIbt/aHdT+/Gc94zCIrBC+6zrBNYRooyAaThpkMOENly9fb1wx2aI4e7U8qFM4GUO9fCYnyDP/w0yD52UesWGkomZU9Y+iWzruMpKWdy89cBiDRVC/OmR2P30Ad4vtl/mSPNwpBQoGsnGpsyv5gniSpkxcxl7V+Klg1VZ9Uh2Vs1tkfmCZh7D3kXQa+eb7Y/R+Jb0Wmrx6mo2kAIlDAL4Ic1Dx0dVU/yXCwCktiztmBR/M/qaEPKzL24HO6gwAsmgp2T7JbCyDcXfn9zBr9xmR8y9iap6/mWcW/CyuMakkK/gYCdKQaEQmGahs1grrzXikyw8zpZqFwDgrWCBSiEZULnlahe2QTmGIjUWiH+Rpv/GhOStOp1bVcxF7mtu2RRCJc+0F5rwM0=
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: el1vFLTfQnkrracoDN3CcXJGCsqzEdmuGs48lJf7L+KDH/GS/nwMCZSp1dOPNg0LrNblM72nr84dwHtxmJUfuzPyq2XZ8lMC/8zIPRkWnaXYloY96I88MgZmC+HIHi1Hc1Wm9On8Fw2SlgzwM5tYLgPrwMokAzM4h7xRges7IwlPkBt9ZtgrHek612kK1+CiEwnciEhWZ4F5EwSioI/Ajb8fRC1CL38vpkuP3nTMLUGs6kNzHds4XAILNjqTo6vwBT/sWtG5SlnkB+jk1dlK/OoQ+EWr5ZTpUFqlCVg4fKcezifDWdlzwViL/r67fBLddHDL3AjuN3G36gFUeHso0WkllgNpII9gJkyd1e82fzT7dNLOdf8EHwQ1s4TL+G26g+/t47Sm+2ceL/t3yeJr9sfjDil78R5IX5vCs7VOMA/mdz6FHH7dUpkqvO0ZHppiHwm9rdouiXsBLCL9dezNZoUi3Y47E7VKJOUiv0RXSVXxa30KImotxGtWA4VWMHvRkHYUn6NVJSj9DTiAsV0bGf5wHA9p+L0MAyPJ28jcwEKq4y+6tGh4zdLwF0nO+ryxzT3TkqPNkPVxSpQY6FdtnRxVYZxbt8XxsLUJuC1rOGvtSRlUqQxB4b+Wzq13j7ug1F8zg4NIyoKzdmWBVGDY3JBHjwz0ruQ4JegHPotJkdQ=
  - secure: 04Boq7mBHQB2Qq3Y7GuLgsPQZ8rC3wyGL8wA1lGbbbcLyO3b88dC4iDui/mPyksj0nGeFwr3OAZDtH+If69HVo88fDlrLzOw3L7XnRHVzA739fECtOQQgK5ykOqmKAGTO79Heo3/F7gtXeWM2m92S6tqnvQFeWubhrEHy/bA1iDcEj0S3+ov6htSife9kRwqlLffviuzLiIFHUTo1jAtImr+z10m1fcMC8YrXgCO7UU5sBRoKBjAb0P5CdpI6dozfQhniEmvm7TItNw5bqpX9RhjvrKD/arOu9eubR997BFUsMe3kaD5qT1oZLPKFYQpVfZL5XBCum9uAvBZZ7MbfwEVxKyOso22WwvMUKmNBVgovP5PXfT7r2COQAiX9rD02ihXky4yMbskb5VfAJqsaypd2hRDtC3WRzLDDpVXX/WEz+zSNz7R3x4Prr+8SQywFZzi4QHQLTVOwafYPVgaDI51GWTmt3spn2sFBMIyKm4w2zAjKQHp9DLPbIEUUp/2xCSK6GIpqt0yyhEEXn5qjyUuqkPiI9/wBSwEeM8hj2rbAtHALWGdji62E2in42PegqHVsVkvHHRtssvPmcI4KXFRPEKYYpwfsWLAJC2zk/lMOp6IqD9lQ2yXtwxo2mNlRy/AxFSRDN2eb3f5PuIKBMDZ/zAMOuSvDiiyW1s7BxU=
